# Generated by Django 5.1.4 on 2025-01-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Business",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fhrs_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField()),
                ("rating", models.CharField(blank=True, max_length=10, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("business_type", models.CharField(max_length=255)),
            ],
        ),
    ]
