# Generated by Django 5.1.4 on 2025-01-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fhrs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="rating",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
