# Generated by Django 5.1.6 on 2025-02-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establishment', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('beverage', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('submitter_name', models.CharField(max_length=255)),
                ('dog_friendly', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
                ('outdoor_seating', models.BooleanField(default=False)),
                ('plant_milks', models.BooleanField(default=False)),
                ('brunch_lunch', models.BooleanField(default=False)),
                ('wheelchair_access', models.BooleanField(default=False)),
                ('coffee_taste', models.IntegerField(default=0)),
                ('coffee_options', models.IntegerField(default=0)),
                ('service', models.IntegerField(default=0)),
                ('atmosphere', models.IntegerField(default=0)),
                ('value_for_money', models.IntegerField(default=0)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts/')),
            ],
        ),
    ]
