# Generated by Django 5.1.6 on 2025-02-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priceapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricesubmission',
            name='beverage',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pricesubmission',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
