# Generated by Django 5.1.6 on 2025-02-19 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('website', models.URLField()),
                ('social_media', models.URLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop_images/')),
                ('opening_times', models.TextField(blank=True, null=True)),
                ('features', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='mycoffeeapp.shop')),
            ],
        ),
        migrations.CreateModel(
            name='PriceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('beverage', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('submitter_name', models.CharField(max_length=255)),
                ('features', models.JSONField()),
                ('ratings', models.JSONField()),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_records', to='mycoffeeapp.shop')),
            ],
        ),
    ]
