# Generated by Django 5.1.6 on 2025-03-17 21:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycoffeeapp', '0004_leaderboard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaderboard',
            options={'ordering': ['-points', 'timestamp']},
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
