# Generated by Django 5.1.6 on 2025-03-20 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycoffeeapp', '0005_alter_leaderboard_options_leaderboard_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaderboard',
            options={'ordering': ['-points']},
        ),
    ]
