# Generated by Django 5.1.6 on 2025-03-03 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('priceapp', '0002_alter_pricesubmission_beverage_and_more'),
    ]

    operations = [
    ]
