# Generated by Django 5.1.6 on 2025-03-20 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priceapp', '0003_force_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricesubmission',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
