name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12.6]  # Ensure GitHub Actions supports this version

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python3 -m pip install --upgrade pip
         pip install --no-cache-dir -r backend/requirements.txt
    - name: Run tests
      working-directory: backend  # Ensure we are inside the backend folder
      run: python3 manage.py test  # Use python3 explicitly

  
